### ISSUE TITLE
Adding a local scope variable breaks the linter

### ISSUE THREAD

**Issue by kokarn** [lesshint/atom-linter-lesshint#1]
For me this code doesn't work
```less
.selector {
    @var: 20px;

    .child {
        margin-left: @var;
    }
}
```

It fails with this error
```
TypeError: Cannot read property 'length' of null
  at [object Object].Lesshint.checkString (/Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/lib/lesshint.js:75:25)
  at Object.lint (/Users/oskarrisberg/.atom/packages/linter-lesshint/index.js:70:43)
  at Promise.then._this.emitter.emit.linter (/Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

**Comment by jwilsson** [comment]
Sorry for the delay on this, I've managed to track it down to a upstream issue with `lesshint`.

When running this with the `1.1.0` version I get the following stack trace:

```
TypeError: Cannot read property 'content' of null
    at Object.propertyUnitsLinter [as lint] (/Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/lib/linters/property_units.js:18:57)
    at /Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/lib/linter.js:101:32
    at Array.forEach (native)
    at /Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/lib/linter.js:86:17
    at Node.traverse (/Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:39:254)
    at Node.traverse (/Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:39:401)
    at Node.traverse (/Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:39:401)
    at Node.traverse (/Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:39:401)
    at Object.exports.lint (/Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/lib/linter.js:85:9)
    at [object Object].Lesshint.checkString (/Users/jonathan.wilsson/.atom/packages/linter-lesshint/node_modules/lesshint/lib/lesshint.js:67:25)
```

I'll create a upstream issue for this.

**Comment by jwilsson** [comment]
This is fixed upstream. I don't know if Atom will include package dependencies when running `apm update`, could you try it out?

**Comment by kokarn** [comment]
Well, people using it won't know it's been updated so I suggest we publish a patch version.

**Comment by jwilsson** [comment]
I've just pushed `1.1.1` which should be picked up by Atom soon.

**Comment by kokarn** [comment]
:+1:
