### ISSUE TITLE
Error with multiple selectors and Allman braces

### ISSUE THREAD

**Issue by wohanley** [lesshint/atom-linter-lesshint#16]
With v2.0.2, this code:

```
.x,
.y
{
}
```

produces this error:

```
Error: Column start (6) greater than line length (3)
    at Object.rangeFromLineNumber (C:\Users\wohanley\.atom\packages\linter-lesshint\node_modules\atom-linter\lib\index.js:186:11)
    at C:/Users/wohanley/.atom/packages/linter-lesshint/index.js:67:43
    at Array.map (native)
    at Object.<anonymous> (C:/Users/wohanley/.atom/packages/linter-lesshint/index.js:64:31)
    at undefined.next (native)
    at step (C:\Users\wohanley\.atom\packages\linter-lesshint\index.js:9:273)
```
This is fine:
```
.x,
.y {
}
```

**Comment by jwilsson** [comment]
I think this is due to https://github.com/lesshint/lesshint/issues/231, lets fix it there.

**Comment by wohanley** [comment]
Ah, sorry, missed that.
