### ISSUE TITLE
Linter breaks on incomplete less

### ISSUE THREAD

**Issue by kokarn** [lesshint/atom-linter-lesshint#2]
Possibly related to #1
Code like this 
```less
.selector {
    .secondselector {

}
```
makes the linter crash with the following message
```
TypeError: Cannot read property 'length' of null
  at [object Object].Lesshint.checkString (/Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/lib/lesshint.js:75:25)
  at Object.lint (/Users/oskarrisberg/.atom/packages/linter-lesshint/index.js:70:43)
  at Promise.then._this.emitter.emit.linter (/Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

**Comment by jwilsson** [comment]
Sorry for the delay on this, could you check it with the latest `1.1.0` and see if the issue still persists?

**Comment by kokarn** [comment]
This is fixed, thanks.
