### ISSUE TITLE
Linter breaks when starting a new file

### ISSUE THREAD

**Issue by kokarn** [lesshint/atom-linter-lesshint#3]
When starting a new file with say
```less
.c
```
before finishing to 
```less
.class {}
```
It throws an error.
```
TypeError: Cannot read property 'column' of undefined
  at Object.spaceBeforeBraceLinter [as lint] (/Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/lib/linters/space_before_brace.js:33:41)
  at /Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/lib/linter.js:101:32
  at Array.forEach (native)
  at /Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/lib/linter.js:86:17
  at Node.traverse (/Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:39:254)
  at Node.traverse (/Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:39:401)
  at Object.exports.lint (/Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/lib/linter.js:85:9)
  at [object Object].Lesshint.checkString (/Users/oskarrisberg/.atom/packages/linter-lesshint/node_modules/lesshint/lib/lesshint.js:67:25)
  at Object.lint (/Users/oskarrisberg/.atom/packages/linter-lesshint/index.js:70:43)
  at Promise.then._this.emitter.emit.linter (/Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /Users/oskarrisberg/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

**Comment by jwilsson** [comment]
Thanks for this.

It's  a upstream issue in `lesshint` as reported as such.

**Comment by jwilsson** [comment]
This is fixed upstream. I don't know if Atom will include package dependencies when running `apm update`, could you try it out?

**Comment by jwilsson** [comment]
I've just pushed `1.1.1` which should be picked up by Atom soon.

**Comment by kokarn** [comment]
:cake:
