### ISSUE TITLE
Failed to activate the linter-lesshint package

### ISSUE THREAD

**Issue by pdxwolfy** [lesshint/atom-linter-lesshint#8]
[Enter steps to reproduce below:]

1. Started atom from command line

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-lesshint](https://github.com/lesshint/atom-linter-lesshint) package, v1.5.0

### Stack Trace

Failed to activate the linter-lesshint package

```
At Cannot find module 'lodash.clonedeep'

Error: Cannot find module 'lodash.clonedeep'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/wolfy/.atom/packages/linter-lesshint/node_modules/lesshint/node_modules/rcfinder/index.js:8:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/wolfy/.atom/packages/linter-lesshint/node_modules/lesshint/lib/config-loader.js:5:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/wolfy/.atom/packages/linter-lesshint/index.js:3:24)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "about",
      "autocomplete-atom-api",
      "autoflow",
      "autosave",
      "background-tips",
      "metrics",
      "timecop",
      "welcome",
      "wrap-guide",
      "archive-view",
      "symbols-view",
      "tree-view-open-files",
      "tree-view-git-branch",
      "linter-tidy"
    ],
    "ignoredNames": [
      "*.a",
      "*.bak",
      "*.class",
      "*.db",
      "*.dds",
      "*.dll",
      "*.dylib",
      "*.eot",
      "*.exe",
      "*.gif",
      "*.ico",
      "*.idb",
      "*.jar",
      "*.jpeg",
      "*.jpg",
      "*.lib",
      "*.ncb",
      "*.o",
      "*.obj",
      "*.pdb",
      "*.pdf",
      "*.png",
      "*.psd",
      "*.pyc",
      "*.pyo",
      "*.sdf",
      "*.so",
      "*.sublime-workspace",
      "*.suo",
      "*.swf",
      "*.tga",
      "*.ttf",
      "*.zip",
      "*~",
      ".DS_Store"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "advanced-open-file"
    ],
    "projectHome": "/Users/wolfy/Atom"
  }
}
```

### Installed Packages

```coffee
# User
atom-sync, v0.7.3
autoclose-html, v0.23.0
chary-tree-view, v0.2.3
file-types, v0.5.1
incsearch, v0.3.3
language-mason, v2.0.4
less-than-slash, v0.13.0
linter, v1.11.4
linter-csslint, v1.3.2
linter-erb, v1.0.2
linter-htmlhint, v1.1.4
linter-js-standard, v3.3.2
linter-jshint, v2.1.0
linter-lesshint, v1.5.0
linter-perl-check-syntax, v0.3.0
linter-perlcritic, v0.3.3
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-ruby-reek, v1.5.1
merge-conflicts, v1.4.2
multi-wrap-guide, v0.23.5
omni-ruler, v0.4.2
open-in-browsers, v0.0.13
plist-converter, v0.1.2
ruby-block, v0.3.5
run-in-browser, v0.1.3
tab-control, v0.6.9
tab-smart-sort, v0.1.4

# Dev
No dev packages
```

**Comment by jwilsson** [comment]
Hmm, it seems I'm unable to reproduce it.

What happens if you uninstall `linter-lesshint` and then install it again?

**Comment by pdxwolfy** [comment]
I manage to uninstall it (though apm complained it did not exist) and then install it. Seems okay now. Thanks.

**Comment by pdxwolfy** [comment]
Oops, no. When I restarted atom, the error was back.

**Comment by pdxwolfy** [comment]
Uninstalled everything, then reinstalled. Seems to have done the trick (for now).
